defmodule Translatable do
  @moduledoc """
  Macro DSL and behaviour for defining translatable messages in source code.

  `use Translatable` makes the current module a message definition module. The
  only public message API generated by the DSL is the literal function declared
  by `defmsg/2`; introspection is available through `__translatable__/1`.

  Message modules are the source of truth for strings that can reach users. A
  message function returns a `%Translatable.Message{}` token with identity and
  bindings, not rendered text. Rendering happens later through a
  `Translatable.Runtime` backend so the same persisted message can be shown in
  different languages for different viewers.

  A typical message module looks like this:

      defmodule MyAppWeb.LoginMessages do
        use Translatable

        translatable_source "en"

        defmsg submit_button() do
          source "Sign in"
          translated_to "es", "Iniciar sesión"
        end

        defmsg greeting(name) do
          translator_note "Shown after the user has successfully signed in."
          param :name, :string, "The display name chosen by the user"
          source "Welcome, {name}"
        end

        defmsg product_name() do
          dont_translate()
          source "Pendulum"
        end
      end

  The `defmsg/2` block is intentionally metadata-first. Parameters, translator
  notes, pre-existing translations, and the source text live beside the function
  that creates the message token. This lets extraction and validation tools use
  the compiled application as their source of truth.

  For very small strings, the shorthand form is also available:

      defmsg ok_button(), as: "OK"

  Message names must be unique within a module. Different arities with the same
  message name are rejected because external translation keys are based on the
  module and local message name, not on the function arity.
  """

  alias Translatable.Definition
  alias Translatable.InvalidMessageError
  alias Translatable.Message
  alias Translatable.Module, as: TranslatableModule
  alias Translatable.Param

  @callback __translatable__(:messages) :: [atom()]
  @callback __translatable__({:definition, atom()}) :: {:ok, Definition.t()} | :error
  @callback __translatable__(:module) :: TranslatableModule.t()

  @doc false
  defmacro __using__(opts) do
    application = Keyword.get_lazy(opts, :application, &default_application/0)
    module = __CALLER__.module

    Module.register_attribute(module, :translatable_application, persist: false)
    Module.register_attribute(module, :translatable_source, persist: false)
    Module.register_attribute(module, :translatable_note, persist: false)
    Module.register_attribute(module, :translatable_params, persist: false)
    Module.register_attribute(module, :translatable_translations, persist: false)
    Module.register_attribute(module, :translatable?, persist: false)
    Module.register_attribute(module, :translatable_definitions, accumulate: true, persist: false)

    Module.put_attribute(module, :translatable_application, application)
    Module.put_attribute(module, :translatable_source, "en")
    Module.put_attribute(module, :translatable_params, %{})
    Module.put_attribute(module, :translatable_translations, %{})
    Module.put_attribute(module, :translatable?, true)

    quote do
      @behaviour Translatable

      import Translatable,
        only: [
          defmsg: 2,
          dont_translate: 0,
          param: 3,
          source: 1,
          translated_to: 2,
          translatable_source: 1,
          translator_note: 1
        ]

      @before_compile Translatable
    end
  end

  @doc """
  Marks the next `defmsg/2` declaration as not requiring translation.
  """
  defmacro dont_translate() do
    Module.put_attribute(__CALLER__.module, :translatable?, false)
    quote(do: :ok)
  end

  @doc """
  Sets the source text inside a `defmsg/2` block.
  """
  defmacro source(_source) do
    raise ArgumentError, "source/1 can only be used inside a defmsg/2 block"
  end

  @doc """
  Sets the source locale for subsequent `defmsg/2` declarations.
  """
  defmacro translatable_source(locale) when is_binary(locale) do
    Module.put_attribute(__CALLER__.module, :translatable_source, locale)
    quote(do: :ok)
  end

  defmacro translatable_source(_locale) do
    raise ArgumentError, "translatable_source/1 expects a literal binary locale"
  end

  @doc """
  Sets the translator note for the next `defmsg/2` declaration.
  """
  defmacro translator_note(note) when is_binary(note) do
    Module.put_attribute(__CALLER__.module, :translatable_note, note)
    quote(do: :ok)
  end

  defmacro translator_note(_note) do
    raise ArgumentError, "translator_note/1 expects a literal binary note"
  end

  @doc """
  Adds parameter metadata for the next `defmsg/2` declaration.
  """
  defmacro param(name, type, note) when is_atom(name) and is_binary(note) do
    params = Module.get_attribute(__CALLER__.module, :translatable_params) || %{}
    param = %Param{name: name, type: type, note: note}
    Module.put_attribute(__CALLER__.module, :translatable_params, Map.put(params, name, param))

    quote(do: :ok)
  end

  defmacro param(_name, _type, _note) do
    raise ArgumentError, "param/3 expects a literal atom name, type, and literal binary note"
  end

  @doc """
  Adds a pre-existing translation for the next `defmsg/2` declaration.
  """
  defmacro translated_to(locale, translation) when is_binary(locale) and is_binary(translation) do
    translations = Module.get_attribute(__CALLER__.module, :translatable_translations) || %{}

    Module.put_attribute(
      __CALLER__.module,
      :translatable_translations,
      Map.put(translations, locale, translation)
    )

    quote(do: :ok)
  end

  defmacro translated_to(_locale, _translation) do
    raise ArgumentError, "translated_to/2 expects literal binary locale and translation"
  end

  @doc """
  Defines a public message function and records its definition metadata.
  """
  defmacro defmsg(call, opts) when is_list(opts) do
    spec = message_spec!(opts, __CALLER__.module)
    emit_defmsg(call, spec, __CALLER__)
  end

  defmacro defmsg(_call, _opts) do
    raise ArgumentError,
          "defmsg/2 requires an :as option, a literal binary source, or a block containing source/1"
  end

  defp emit_defmsg(call, spec, caller) do
    {name, args} = decompose_call!(call)
    arg_names = Enum.map(args, &var_name!/1)
    binding_ast = binding_map_ast(arg_names)
    module = caller.module
    application = Module.get_attribute(module, :translatable_application)

    definition =
      build_definition(
        module,
        application,
        name,
        length(args),
        Module.get_attribute(module, :translatable_source),
        spec.source,
        spec.params,
        spec.translator_note,
        spec.translations,
        spec.translatable?,
        arg_names,
        {caller.file, caller.line}
      )

    emit_definition_warnings(definition)
    Module.put_attribute(module, :translatable_definitions, definition)
    clear_legacy_message_attributes(module)

    function_ast =
      if definition.valid? do
        quote do
          def unquote(name)(unquote_splicing(args)) do
            %Message{
              application: unquote(application),
              module: __MODULE__,
              name: unquote(name),
              bindings: unquote(binding_ast)
            }
          end
        end
      else
        quote do
          def unquote(name)(unquote_splicing(args)) do
            raise InvalidMessageError,
              module: __MODULE__,
              name: unquote(name),
              errors: unquote(Macro.escape(definition.errors))
          end
        end
      end

    quote do
      unquote(function_ast)
    end
  end

  @doc false
  defmacro __before_compile__(env) do
    definitions =
      env.module
      |> Module.get_attribute(:translatable_definitions)
      |> Enum.reverse()

    duplicate_names = duplicate_values(Enum.map(definitions, & &1.name))
    Enum.each(duplicate_names, &warn_duplicate_message_name(env.module, &1))

    message_names = Enum.map(definitions, & &1.name)

    definition_clauses = definition_clauses(definitions, duplicate_names)

    application = Module.get_attribute(env.module, :translatable_application)
    source_locale = Module.get_attribute(env.module, :translatable_source)

    quote do
      @impl Translatable
      def __translatable__(:messages), do: unquote(message_names)

      unquote_splicing(definition_clauses)

      def __translatable__({:definition, _name}), do: :error

      @impl Translatable
      def __translatable__(:module) do
        %TranslatableModule{
          application: unquote(application),
          module: __MODULE__,
          source_locale: unquote(source_locale),
          messages:
            Enum.map(__translatable__(:messages), fn name ->
              {:ok, definition} = __translatable__({:definition, name})
              definition
            end)
        }
      end
    end
  end

  defp message_spec!(opts, module) do
    cond do
      Keyword.has_key?(opts, :as) ->
        warn_if_legacy_message_attributes_pending(module, ":as")
        source = fetch_as_source!(opts)

        %{
          source: source,
          params: %{},
          translator_note: nil,
          translations: %{},
          translatable?: true
        }

      Keyword.has_key?(opts, :do) ->
        case Keyword.fetch!(opts, :do) do
          block ->
            warn_if_legacy_message_attributes_pending(module, "block")
            parse_message_block!(block)
        end

      true ->
        raise ArgumentError,
              "defmsg/2 requires an :as option, a literal binary source, or a block containing source/1"
    end
  end

  defp warn_if_legacy_message_attributes_pending(module, form) do
    if legacy_message_attributes_pending?(module) do
      IO.warn(
        "Translatable #{inspect(module)} has pending message directives before defmsg/2 #{form} form; move directives inside the defmsg block to attach metadata to the message"
      )
    end
  end

  defp legacy_message_attributes_pending?(module) do
    Module.get_attribute(module, :translatable_note) not in [nil, ""] or
      map_size(Module.get_attribute(module, :translatable_params) || %{}) > 0 or
      map_size(Module.get_attribute(module, :translatable_translations) || %{}) > 0 or
      Module.get_attribute(module, :translatable?) == false
  end

  defp fetch_as_source!(opts) do
    case Keyword.fetch(opts, :as) do
      {:ok, source} when is_binary(source) ->
        source

      {:ok, _source} ->
        raise ArgumentError, "defmsg/2 :as option requires a literal binary source"

      :error ->
        raise ArgumentError, "defmsg/2 keyword form requires an :as option"
    end
  end

  defp clear_legacy_message_attributes(module) do
    Module.put_attribute(module, :translatable_note, nil)
    Module.put_attribute(module, :translatable_params, %{})
    Module.put_attribute(module, :translatable_translations, %{})
    Module.put_attribute(module, :translatable?, true)
  end

  defp parse_message_block!(block) do
    block
    |> block_expressions()
    |> Enum.reduce(
      %{source: nil, params: %{}, translator_note: nil, translations: %{}, translatable?: true},
      &parse_message_directive!/2
    )
    |> require_message_source!()
  end

  defp block_expressions({:__block__, _meta, expressions}), do: expressions
  defp block_expressions(expression), do: [expression]

  defp parse_message_directive!({:source, _meta, [source]}, spec) when is_binary(source) do
    if spec.source do
      raise ArgumentError, "defmsg/2 block can only contain one source/1 directive"
    end

    %{spec | source: source}
  end

  defp parse_message_directive!({:source, _meta, _args}, _spec) do
    raise ArgumentError, "source/1 requires a literal binary source inside a defmsg/2 block"
  end

  defp parse_message_directive!({:translator_note, _meta, [note]}, spec) when is_binary(note) do
    %{spec | translator_note: note}
  end

  defp parse_message_directive!({:param, _meta, [name, type, note]}, spec)
       when is_atom(name) and is_binary(note) do
    param = %Param{name: name, type: type, note: note}
    %{spec | params: Map.put(spec.params, name, param)}
  end

  defp parse_message_directive!({:translated_to, _meta, [locale, translation]}, spec)
       when is_binary(locale) and is_binary(translation) do
    %{spec | translations: Map.put(spec.translations, locale, translation)}
  end

  defp parse_message_directive!({:dont_translate, _meta, []}, spec) do
    %{spec | translatable?: false}
  end

  defp parse_message_directive!({:dont_translate, _meta, nil}, spec) do
    %{spec | translatable?: false}
  end

  defp parse_message_directive!(directive, _spec) do
    raise ArgumentError,
          "defmsg/2 block contains unsupported directive #{Macro.to_string(directive)}"
  end

  defp require_message_source!(%{source: source} = spec) when is_binary(source), do: spec

  defp require_message_source!(_spec) do
    raise ArgumentError,
          "defmsg/2 block requires a source/1 directive with a literal binary source"
  end

  defp build_definition(
         module,
         application,
         name,
         arity,
         source_locale,
         source,
         params,
         translator_note,
         translations,
         translatable?,
         arg_names,
         location
       ) do
    errors =
      []
      |> validate_param_arguments(params, arg_names)
      |> validate_source_params(source, params)
      |> validate_translation_params(translations, params)

    %Definition{
      application: application,
      module: module,
      name: name,
      arity: arity,
      source_locale: source_locale,
      source: source,
      params: params,
      translator_note: translator_note,
      translations: translations,
      translatable?: translatable?,
      location: location,
      errors: Enum.reverse(errors),
      valid?: errors == []
    }
  end

  defp emit_definition_warnings(%Definition{errors: []}), do: :ok

  defp emit_definition_warnings(%Definition{} = definition) do
    Enum.each(definition.errors, fn error ->
      IO.warn("Translatable #{inspect(definition.module)}.#{definition.name}: #{error}")
    end)
  end

  defp definition_clauses(definitions, duplicate_names) do
    definitions
    |> Enum.group_by(& &1.name)
    |> Enum.sort_by(fn {name, _definitions} -> Atom.to_string(name) end)
    |> Enum.map(fn {name, definitions} ->
      if name in duplicate_names do
        duplicate_definition_clause(name)
      else
        [definition] = definitions
        definition_clause(definition)
      end
    end)
  end

  defp definition_clause(%Definition{name: name} = definition) do
    quote do
      def __translatable__({:definition, unquote(name)}) do
        {:ok, unquote(Macro.escape(definition))}
      end
    end
  end

  defp duplicate_definition_clause(name) do
    error = "duplicate message name #{inspect(name)}"

    quote do
      def __translatable__({:definition, unquote(name)}) do
        raise InvalidMessageError,
          module: __MODULE__,
          name: unquote(name),
          errors: [unquote(error)]
      end
    end
  end

  defp warn_duplicate_message_name(module, name) do
    IO.warn(
      "Translatable #{inspect(module)} defines duplicate message name #{inspect(name)}; message names must be unique within a module"
    )
  end

  defp validate_param_arguments(errors, params, arg_names) do
    param_names = Map.keys(params)
    missing_args = param_names -- arg_names
    undeclared_args = arg_names -- param_names

    errors
    |> append_errors(
      missing_args,
      &"declared parameter #{inspect(&1)} is not a function argument"
    )
    |> append_errors(
      undeclared_args,
      &"function argument #{inspect(&1)} has no parameter declaration"
    )
  end

  defp validate_source_params(errors, source, params) do
    validate_text_params(errors, "source", source, params)
  end

  defp validate_translation_params(errors, translations, params) do
    Enum.reduce(translations, errors, fn {locale, translation}, acc ->
      validate_text_params(acc, "translation #{inspect(locale)}", translation, params)
    end)
  end

  defp validate_text_params(errors, label, text, params) do
    declared = Map.keys(params)
    declared_names = Enum.map(declared, &Atom.to_string/1)
    referenced_names = referenced_param_names(text)
    undeclared_names = referenced_names -- declared_names
    missing_references = Enum.reject(declared, &(Atom.to_string(&1) in referenced_names))

    errors
    |> append_errors(
      undeclared_names,
      &"#{label} references undeclared parameter :#{&1}"
    )
    |> append_errors(
      missing_references,
      &"#{label} does not reference declared parameter #{inspect(&1)}"
    )
  end

  defp append_errors(errors, values, fun) do
    Enum.reduce(values, errors, fn value, acc -> [fun.(value) | acc] end)
  end

  defp duplicate_values(values) do
    values
    |> Enum.reduce({MapSet.new(), MapSet.new()}, fn value, {seen, duplicates} ->
      if MapSet.member?(seen, value) do
        {seen, MapSet.put(duplicates, value)}
      else
        {MapSet.put(seen, value), duplicates}
      end
    end)
    |> elem(1)
    |> MapSet.to_list()
  end

  defp referenced_param_names(text) do
    text
    |> String.to_charlist()
    |> scan_icu_message([])
    |> Enum.reverse()
    |> Enum.uniq()
    |> Enum.map(&to_string/1)
  end

  defp scan_icu_message([], names), do: names

  defp scan_icu_message([?{ | rest], names) do
    {rest, names} = scan_icu_placeholder(rest, names)
    scan_icu_message(rest, names)
  end

  defp scan_icu_message([_char | rest], names), do: scan_icu_message(rest, names)

  defp scan_icu_placeholder(chars, names) do
    chars = skip_icu_whitespace(chars)
    {name, chars} = take_icu_identifier(chars, [])
    chars = skip_icu_whitespace(chars)

    case {name, chars} do
      {[], chars} ->
        skip_icu_placeholder(chars, 1)

      {name, [?} | rest]} ->
        {rest, [name | names]}

      {name, [?, | rest]} ->
        {body, rest} = take_icu_placeholder_body(rest, 1, [])
        names = scan_icu_format_body(body, [name | names])
        {rest, names}

      {_name, chars} ->
        skip_icu_placeholder(chars, 1)
    end
  end

  defp scan_icu_format_body([], names), do: names

  defp scan_icu_format_body([?{ | rest], names) do
    {message, rest} = take_icu_placeholder_body(rest, 1, [])
    names = scan_icu_message(message, names)
    scan_icu_format_body(rest, names)
  end

  defp scan_icu_format_body([_char | rest], names), do: scan_icu_format_body(rest, names)

  defp take_icu_identifier([char | rest], chars)
       when char in ?a..?z or char in ?A..?Z or char == ?_ do
    take_icu_identifier_tail(rest, [char | chars])
  end

  defp take_icu_identifier(chars, _acc), do: {[], chars}

  defp take_icu_identifier_tail([char | rest], chars)
       when char in ?a..?z or char in ?A..?Z or char in ?0..?9 or char == ?_ do
    take_icu_identifier_tail(rest, [char | chars])
  end

  defp take_icu_identifier_tail(chars, acc), do: {Enum.reverse(acc), chars}

  defp take_icu_placeholder_body([], _depth, acc), do: {Enum.reverse(acc), []}
  defp take_icu_placeholder_body([?} | rest], 1, acc), do: {Enum.reverse(acc), rest}

  defp take_icu_placeholder_body([?} | rest], depth, acc) do
    take_icu_placeholder_body(rest, depth - 1, [?} | acc])
  end

  defp take_icu_placeholder_body([?{ | rest], depth, acc) do
    take_icu_placeholder_body(rest, depth + 1, [?{ | acc])
  end

  defp take_icu_placeholder_body([char | rest], depth, acc) do
    take_icu_placeholder_body(rest, depth, [char | acc])
  end

  defp skip_icu_placeholder([], _depth), do: {[], []}
  defp skip_icu_placeholder([?} | rest], 1), do: {rest, []}
  defp skip_icu_placeholder([?} | rest], depth), do: skip_icu_placeholder(rest, depth - 1)
  defp skip_icu_placeholder([?{ | rest], depth), do: skip_icu_placeholder(rest, depth + 1)
  defp skip_icu_placeholder([_char | rest], depth), do: skip_icu_placeholder(rest, depth)

  defp skip_icu_whitespace([char | rest]) when char in [?\s, ?\n, ?\r, ?\t] do
    skip_icu_whitespace(rest)
  end

  defp skip_icu_whitespace(chars), do: chars

  defp decompose_call!({name, _meta, args}) when is_atom(name) and is_list(args), do: {name, args}
  defp decompose_call!(name) when is_atom(name), do: {name, []}

  defp decompose_call!(_call) do
    raise ArgumentError, "defmsg/2 expects a local function call such as ready_self(total, ready)"
  end

  defp var_name!({name, _meta, context}) when is_atom(name) and is_atom(context), do: name

  defp var_name!(_arg) do
    raise ArgumentError, "defmsg/2 arguments must be plain variables"
  end

  defp binding_map_ast(arg_names) do
    pairs =
      Enum.map(arg_names, fn name ->
        {name, {name, [], nil}}
      end)

    {:%{}, [], pairs}
  end

  defp default_application do
    if Code.ensure_loaded?(Mix.Project) do
      Mix.Project.config()[:app] || :translatable
    else
      :translatable
    end
  end
end
