#!/usr/bin/env sh
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

"$SCRIPT_DIR/test-elixir" "1.15.8-erlang-26.2.5-debian-bookworm-20240701-slim"
"$SCRIPT_DIR/test-elixir" "1.16.3-erlang-26.2.5-debian-bookworm-20240701-slim"
"$SCRIPT_DIR/test-elixir" "1.17.3-erlang-27.1.2-debian-bookworm-20241111-slim"
"$SCRIPT_DIR/test-elixir" "1.18.4-erlang-27.3.4-debian-bookworm-20250610-slim"
