#!/usr/bin/env sh
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

"$SCRIPT_DIR/test-elixir" "elixir:1.15.8-otp-26"
"$SCRIPT_DIR/test-elixir" "elixir:1.16.3-otp-26"
"$SCRIPT_DIR/test-elixir" "elixir:1.17.3-otp-27"
"$SCRIPT_DIR/test-elixir" "elixir:1.18.4-otp-27"
